// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

import edu.wpi.first.wpilibj.RobotBase;

/** Program entry point generated by WPILib. */
public final class Main {
  /** Prevents this utility class from being constructed. */
  private Main() {}

  /**
   * Starts the robot program and tells WPILib to create the {@link Robot}
   * instance that owns the robot lifecycle.
   */
  public static void main(String... args) {
    RobotBase.startRobot(Robot::new);
  }
}
